### ISSUE TITLE
Error:Failed to resolve: com.github.yoojia:zxing:1.0.1

### ISSUE THREAD

**Issue by f9021003** [yoojia/ZXingMini#4]
hi
我剛剛新增一個project,並且在build.gradle中 加入:
dependencies {
    compile 'com.github.yoojia:zxing:1.0.1@aar'

}

但在syn階段時,  回報Error:Failed to resolve: com.github.yoojia:zxing:1.0.1
請問一下 要如何解決呢?

(我在"https://bintray.com/search?query=yoojia" 這裡並沒有查到 ArtifactId = zxing)

謝謝您

**Comment by yoojia** [comment]
在Bintray中出现了问题。现在版本号是0.7可以正常使用了。感谢你发现的问题。
